#!/usr/bin/env python
from constants import MAPGEN_PATH
import cgitb
cgitb.enable()
import sys
sys.stderr = sys.stdout
sys.path.insert(0,MAPGEN_PATH)
import trials
from mapgen import format
print 'Content-type: text/html'
print
print '''<html><head>
<title>Conquest of Elysium 3 - Trial By Fire</title> 
<link rel="stylesheet" type="text/css" href="../css/style.css" />
</head><body>
<h1>Trial by Fire</h1>
<ol>
'''
for i,trial in enumerate(trials.TRIALS):
   print format('<li><a href="trial?t={0}">{1}</a></li>', i+1, trial['title'])

print '''</ol>
</body></html>'''
