#!/usr/bin/env python
from constants import MAPGEN_PATH
import cgitb
cgitb.enable()
import cgi
import sys
sys.stderr = sys.stdout
sys.path.insert(0,MAPGEN_PATH)
import trials
from mapgen import format, CLASS, AI, SOCIETY, MAPSIZE, MAP_DIMS

form = cgi.FieldStorage()

COLORS = [ (22,90,18), (90,27,18), (18,40,90), (90,88,18), 
           (18,77,90), (90,18,86), (90,63,18), (49,18,90) ]

def player_color(player):
   color = COLORS[player-1]
   return format('rgb({0},{1},{2})',*color)

def player_block(player):
   color = player_color(player)
   return format('<div class="colorblock" style="outline-color: {0}; background-color: {1}" temp="{2}" ></div>',color,color,player)

try:
   trial = trials.TRIALS[int(form["t"].value)-1]
except:
   print 'Location: trials.cgi'
   print

print 'Content-type: text/html'
print
print '<html><head>'
print '<title>Conquest of Elysium 3 - Trial By Fire -', trial['title'],
print '''</title> 
      <link rel="stylesheet" type="text/css" href="../css/style.css" />
      </head>
      <body>'''
print '<a href="/">Home</a>&nbsp;&lt;&nbsp;<a href="trials.cgi">List of Trials</a>'
print '<h1>',trial['title'],'</h1>'
print '<p>',trial['desc'],'</p>'
    
print '<ul>'
map_url = trial.get('options',{}).get('map url',None)
if map_url:
   print '<li> <a href="',map_url,'">Map URL</a></li>'
else:
   mapdim = MAP_DIMS[trial['map_size']]
   print '<li>',format("Map Size: {0} ({1}x{2})",
         MAPSIZE[trial['map_size']],mapdim[0], mapdim[1]),'</li>'
   print '<li>',format("Society: {0} ({1})",SOCIETY[trial["society"]], 
               trial['society']),'</li>'
   optmap = {True: 'On', False: 'Off'}
   for k,v in trial.get('options',{}).iteritems():
      print '<li>',format("{0}: {1}",k,optmap[v]),'</li>'
print '</ul>'

players = trials.pick_players(trial['classes'],trial['levels'],
                   trial.get('teams',None),trial.get('sets',None))
if len(players):
   print '<table><tr><th>Player</th><th>Class</th><th>Controller /<br>Difficulty</th><th>Team</th></tr>'
   for i, c, l, t in players:         
      print format('<tr><td style="text-align: center">{0}</td><td>{1}</td><td>{2}</td><td>{3}</td></tr>', player_block(i), CLASS[c],AI[l],t)
   print '</table>' 

print '</body></html>'
